site_name: invoicer
site_description: Test project
repo_url: https://github.com/raizanshine/test-invoicer
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/raizanshine">raizanshine</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
